<?php
/**
 * ResourcesDiscoverApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BuiltByBit API
 *
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ResourcesDiscoverApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourcesDiscoverApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getResourcesDiscoverCategories' => [
            'application/json',
        ],
        'getResourcesDiscoverResources' => [
            'application/json',
        ],
        'getV2ResourcesDiscoverDownloadDirectInitiate' => [
            'application/json',
        ],
        'getV2ResourcesDiscoverDownloadDirectPoll' => [
            'application/json',
        ],
        'getV2ResourcesDiscoverLicenses' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getResourcesDiscoverCategories
     *
     * Fetch a list of categories
     *
     * @param  string $category_id A category ID to filter on. (optional)
     * @param  string $with A comma-separated list of submodels to include. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverCategories'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse
     */
    public function getResourcesDiscoverCategories($category_id = null, $with = null, string $contentType = self::contentTypes['getResourcesDiscoverCategories'][0])
    {
        list($response) = $this->getResourcesDiscoverCategoriesWithHttpInfo($category_id, $with, $contentType);
        return $response;
    }

    /**
     * Operation getResourcesDiscoverCategoriesWithHttpInfo
     *
     * Fetch a list of categories
     *
     * @param  string $category_id A category ID to filter on. (optional)
     * @param  string $with A comma-separated list of submodels to include. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverCategories'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getResourcesDiscoverCategoriesWithHttpInfo($category_id = null, $with = null, string $contentType = self::contentTypes['getResourcesDiscoverCategories'][0])
    {
        $request = $this->getResourcesDiscoverCategoriesRequest($category_id, $with, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
                
            }

            $returnType = '\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
                
            }
            throw $e;
        }
    }

    /**
     * Operation getResourcesDiscoverCategoriesAsync
     *
     * Fetch a list of categories
     *
     * @param  string $category_id A category ID to filter on. (optional)
     * @param  string $with A comma-separated list of submodels to include. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverCategories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getResourcesDiscoverCategoriesAsync($category_id = null, $with = null, string $contentType = self::contentTypes['getResourcesDiscoverCategories'][0])
    {
        return $this->getResourcesDiscoverCategoriesAsyncWithHttpInfo($category_id, $with, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getResourcesDiscoverCategoriesAsyncWithHttpInfo
     *
     * Fetch a list of categories
     *
     * @param  string $category_id A category ID to filter on. (optional)
     * @param  string $with A comma-separated list of submodels to include. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverCategories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getResourcesDiscoverCategoriesAsyncWithHttpInfo($category_id = null, $with = null, string $contentType = self::contentTypes['getResourcesDiscoverCategories'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetResourcesDiscoverCategories200Response';
        $request = $this->getResourcesDiscoverCategoriesRequest($category_id, $with, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getResourcesDiscoverCategories'
     *
     * @param  string $category_id A category ID to filter on. (optional)
     * @param  string $with A comma-separated list of submodels to include. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverCategories'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getResourcesDiscoverCategoriesRequest($category_id = null, $with = null, string $contentType = self::contentTypes['getResourcesDiscoverCategories'][0])
    {




        $resourcePath = '/v2/resources/discover/categories';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category_id,
            'category_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with,
            'with', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getResourcesDiscoverResources
     *
     * Fetch a list of resources
     *
     * @param  string $category_id A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param  string $with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param  object $filters A list of dynamic filters to apply. (optional)
     * @param  string $resource_ids A comma-separated list of resource IDs to filter on. (optional)
     * @param  int $page The page number to return. (optional, default to 1)
     * @param  float $per_page The number of resources to return per page. (optional, default to 25)
     * @param  bool $no_dependencies Whether or not to exclude resources with dependencies listed. (optional)
     * @param  string $excluded_resource_ids A comma-separated list of resource IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $excluded_creator_ids A comma-separated list of creator IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverResources'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetResourcesDiscoverResources200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse
     */
    public function getResourcesDiscoverResources($category_id = null, $with = null, $filters = null, $resource_ids = null, $page = 1, $per_page = 25, $no_dependencies = null, $excluded_resource_ids = null, $excluded_creator_ids = null, string $contentType = self::contentTypes['getResourcesDiscoverResources'][0])
    {
        list($response) = $this->getResourcesDiscoverResourcesWithHttpInfo($category_id, $with, $filters, $resource_ids, $page, $per_page, $no_dependencies, $excluded_resource_ids, $excluded_creator_ids, $contentType);
        return $response;
    }

    /**
     * Operation getResourcesDiscoverResourcesWithHttpInfo
     *
     * Fetch a list of resources
     *
     * @param  string $category_id A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param  string $with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param  object $filters A list of dynamic filters to apply. (optional)
     * @param  string $resource_ids A comma-separated list of resource IDs to filter on. (optional)
     * @param  int $page The page number to return. (optional, default to 1)
     * @param  float $per_page The number of resources to return per page. (optional, default to 25)
     * @param  bool $no_dependencies Whether or not to exclude resources with dependencies listed. (optional)
     * @param  string $excluded_resource_ids A comma-separated list of resource IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $excluded_creator_ids A comma-separated list of creator IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverResources'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetResourcesDiscoverResources200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getResourcesDiscoverResourcesWithHttpInfo($category_id = null, $with = null, $filters = null, $resource_ids = null, $page = 1, $per_page = 25, $no_dependencies = null, $excluded_resource_ids = null, $excluded_creator_ids = null, string $contentType = self::contentTypes['getResourcesDiscoverResources'][0])
    {
        $request = $this->getResourcesDiscoverResourcesRequest($category_id, $with, $filters, $resource_ids, $page, $per_page, $no_dependencies, $excluded_resource_ids, $excluded_creator_ids, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
                
            }

            $returnType = '\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
                
            }
            throw $e;
        }
    }

    /**
     * Operation getResourcesDiscoverResourcesAsync
     *
     * Fetch a list of resources
     *
     * @param  string $category_id A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param  string $with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param  object $filters A list of dynamic filters to apply. (optional)
     * @param  string $resource_ids A comma-separated list of resource IDs to filter on. (optional)
     * @param  int $page The page number to return. (optional, default to 1)
     * @param  float $per_page The number of resources to return per page. (optional, default to 25)
     * @param  bool $no_dependencies Whether or not to exclude resources with dependencies listed. (optional)
     * @param  string $excluded_resource_ids A comma-separated list of resource IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $excluded_creator_ids A comma-separated list of creator IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverResources'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getResourcesDiscoverResourcesAsync($category_id = null, $with = null, $filters = null, $resource_ids = null, $page = 1, $per_page = 25, $no_dependencies = null, $excluded_resource_ids = null, $excluded_creator_ids = null, string $contentType = self::contentTypes['getResourcesDiscoverResources'][0])
    {
        return $this->getResourcesDiscoverResourcesAsyncWithHttpInfo($category_id, $with, $filters, $resource_ids, $page, $per_page, $no_dependencies, $excluded_resource_ids, $excluded_creator_ids, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getResourcesDiscoverResourcesAsyncWithHttpInfo
     *
     * Fetch a list of resources
     *
     * @param  string $category_id A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param  string $with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param  object $filters A list of dynamic filters to apply. (optional)
     * @param  string $resource_ids A comma-separated list of resource IDs to filter on. (optional)
     * @param  int $page The page number to return. (optional, default to 1)
     * @param  float $per_page The number of resources to return per page. (optional, default to 25)
     * @param  bool $no_dependencies Whether or not to exclude resources with dependencies listed. (optional)
     * @param  string $excluded_resource_ids A comma-separated list of resource IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $excluded_creator_ids A comma-separated list of creator IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverResources'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getResourcesDiscoverResourcesAsyncWithHttpInfo($category_id = null, $with = null, $filters = null, $resource_ids = null, $page = 1, $per_page = 25, $no_dependencies = null, $excluded_resource_ids = null, $excluded_creator_ids = null, string $contentType = self::contentTypes['getResourcesDiscoverResources'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetResourcesDiscoverResources200Response';
        $request = $this->getResourcesDiscoverResourcesRequest($category_id, $with, $filters, $resource_ids, $page, $per_page, $no_dependencies, $excluded_resource_ids, $excluded_creator_ids, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getResourcesDiscoverResources'
     *
     * @param  string $category_id A category ID to filter on. If the provided category is a parent, resources from subcategories will also be included. (optional)
     * @param  string $with A comma-separated list of additional data to include. See endpoint documentation for more information. (optional)
     * @param  object $filters A list of dynamic filters to apply. (optional)
     * @param  string $resource_ids A comma-separated list of resource IDs to filter on. (optional)
     * @param  int $page The page number to return. (optional, default to 1)
     * @param  float $per_page The number of resources to return per page. (optional, default to 25)
     * @param  bool $no_dependencies Whether or not to exclude resources with dependencies listed. (optional)
     * @param  string $excluded_resource_ids A comma-separated list of resource IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $excluded_creator_ids A comma-separated list of creator IDs to exclude. No filter will be applied if empty. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getResourcesDiscoverResources'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getResourcesDiscoverResourcesRequest($category_id = null, $with = null, $filters = null, $resource_ids = null, $page = 1, $per_page = 25, $no_dependencies = null, $excluded_resource_ids = null, $excluded_creator_ids = null, string $contentType = self::contentTypes['getResourcesDiscoverResources'][0])
    {






        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ResourcesDiscoverApi.getResourcesDiscoverResources, must be smaller than or equal to 100.');
        }
        




        $resourcePath = '/v2/resources/discover/resources';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category_id,
            'category_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with,
            'with', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filters,
            'filters', // param base name
            'object', // openApiType
            'deepObject', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resource_ids,
            'resource_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_dependencies,
            'no_dependencies', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $excluded_resource_ids,
            'excluded_resource_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $excluded_creator_ids,
            'excluded_creator_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectInitiate
     *
     * Initiate a direct download request
     *
     * @param  string $content_type Either &#39;resource&#39; or &#39;resource_version&#39; (required)
     * @param  int $content_id content_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response
     */
    public function getV2ResourcesDiscoverDownloadDirectInitiate($content_type, $content_id, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'][0])
    {
        list($response) = $this->getV2ResourcesDiscoverDownloadDirectInitiateWithHttpInfo($content_type, $content_id, $contentType);
        return $response;
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectInitiateWithHttpInfo
     *
     * Initiate a direct download request
     *
     * @param  string $content_type Either &#39;resource&#39; or &#39;resource_version&#39; (required)
     * @param  int $content_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2ResourcesDiscoverDownloadDirectInitiateWithHttpInfo($content_type, $content_id, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'][0])
    {
        $request = $this->getV2ResourcesDiscoverDownloadDirectInitiateRequest($content_type, $content_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectInitiateAsync
     *
     * Initiate a direct download request
     *
     * @param  string $content_type Either &#39;resource&#39; or &#39;resource_version&#39; (required)
     * @param  int $content_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverDownloadDirectInitiateAsync($content_type, $content_id, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'][0])
    {
        return $this->getV2ResourcesDiscoverDownloadDirectInitiateAsyncWithHttpInfo($content_type, $content_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectInitiateAsyncWithHttpInfo
     *
     * Initiate a direct download request
     *
     * @param  string $content_type Either &#39;resource&#39; or &#39;resource_version&#39; (required)
     * @param  int $content_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverDownloadDirectInitiateAsyncWithHttpInfo($content_type, $content_id, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectInitiate200Response';
        $request = $this->getV2ResourcesDiscoverDownloadDirectInitiateRequest($content_type, $content_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2ResourcesDiscoverDownloadDirectInitiate'
     *
     * @param  string $content_type Either &#39;resource&#39; or &#39;resource_version&#39; (required)
     * @param  int $content_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getV2ResourcesDiscoverDownloadDirectInitiateRequest($content_type, $content_id, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectInitiate'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getV2ResourcesDiscoverDownloadDirectInitiate'
            );
        }

        // verify the required parameter 'content_id' is set
        if ($content_id === null || (is_array($content_id) && count($content_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_id when calling getV2ResourcesDiscoverDownloadDirectInitiate'
            );
        }


        $resourcePath = '/v2/resources/discover/download/direct/initiate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $content_type,
            'content_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $content_id,
            'content_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectPoll
     *
     * Fetch the status of a direct download request
     *
     * @param  string $token The download request token returned from an initiate request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response
     */
    public function getV2ResourcesDiscoverDownloadDirectPoll($token = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'][0])
    {
        list($response) = $this->getV2ResourcesDiscoverDownloadDirectPollWithHttpInfo($token, $contentType);
        return $response;
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectPollWithHttpInfo
     *
     * Fetch the status of a direct download request
     *
     * @param  string $token The download request token returned from an initiate request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2ResourcesDiscoverDownloadDirectPollWithHttpInfo($token = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'][0])
    {
        $request = $this->getV2ResourcesDiscoverDownloadDirectPollRequest($token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectPollAsync
     *
     * Fetch the status of a direct download request
     *
     * @param  string $token The download request token returned from an initiate request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverDownloadDirectPollAsync($token = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'][0])
    {
        return $this->getV2ResourcesDiscoverDownloadDirectPollAsyncWithHttpInfo($token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getV2ResourcesDiscoverDownloadDirectPollAsyncWithHttpInfo
     *
     * Fetch the status of a direct download request
     *
     * @param  string $token The download request token returned from an initiate request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverDownloadDirectPollAsyncWithHttpInfo($token = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverDownloadDirectPoll200Response';
        $request = $this->getV2ResourcesDiscoverDownloadDirectPollRequest($token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2ResourcesDiscoverDownloadDirectPoll'
     *
     * @param  string $token The download request token returned from an initiate request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getV2ResourcesDiscoverDownloadDirectPollRequest($token = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverDownloadDirectPoll'][0])
    {



        $resourcePath = '/v2/resources/discover/download/direct/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2ResourcesDiscoverLicenses
     *
     * Fetch a list of the user&#39;s licenses
     *
     * @param  int $page The page number/offset to return items for. (optional)
     * @param  int $per_page The number of items per page to return. (optional, default to 25)
     * @param  string $with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverLicenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse
     */
    public function getV2ResourcesDiscoverLicenses($page = null, $per_page = 25, $with = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverLicenses'][0])
    {
        list($response) = $this->getV2ResourcesDiscoverLicensesWithHttpInfo($page, $per_page, $with, $contentType);
        return $response;
    }

    /**
     * Operation getV2ResourcesDiscoverLicensesWithHttpInfo
     *
     * Fetch a list of the user&#39;s licenses
     *
     * @param  int $page The page number/offset to return items for. (optional)
     * @param  int $per_page The number of items per page to return. (optional, default to 25)
     * @param  string $with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverLicenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse|\OpenAPI\Client\Model\GetResourcesDiscoverResources4XXResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2ResourcesDiscoverLicensesWithHttpInfo($page = null, $per_page = 25, $with = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverLicenses'][0])
    {
        $request = $this->getV2ResourcesDiscoverLicensesRequest($page, $per_page, $with, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
                
            }

            $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
                
            }
            throw $e;
        }
    }

    /**
     * Operation getV2ResourcesDiscoverLicensesAsync
     *
     * Fetch a list of the user&#39;s licenses
     *
     * @param  int $page The page number/offset to return items for. (optional)
     * @param  int $per_page The number of items per page to return. (optional, default to 25)
     * @param  string $with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverLicensesAsync($page = null, $per_page = 25, $with = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverLicenses'][0])
    {
        return $this->getV2ResourcesDiscoverLicensesAsyncWithHttpInfo($page, $per_page, $with, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getV2ResourcesDiscoverLicensesAsyncWithHttpInfo
     *
     * Fetch a list of the user&#39;s licenses
     *
     * @param  int $page The page number/offset to return items for. (optional)
     * @param  int $per_page The number of items per page to return. (optional, default to 25)
     * @param  string $with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getV2ResourcesDiscoverLicensesAsyncWithHttpInfo($page = null, $per_page = 25, $with = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverLicenses'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetV2ResourcesDiscoverLicenses200Response';
        $request = $this->getV2ResourcesDiscoverLicensesRequest($page, $per_page, $with, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2ResourcesDiscoverLicenses'
     *
     * @param  int $page The page number/offset to return items for. (optional)
     * @param  int $per_page The number of items per page to return. (optional, default to 25)
     * @param  string $with A comma-separated list of supported &#39;with hints&#39;. See model &amp; endpoint-level docs for more info. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getV2ResourcesDiscoverLicenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getV2ResourcesDiscoverLicensesRequest($page = null, $per_page = 25, $with = null, string $contentType = self::contentTypes['getV2ResourcesDiscoverLicenses'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling ResourcesDiscoverApi.getV2ResourcesDiscoverLicenses, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ResourcesDiscoverApi.getV2ResourcesDiscoverLicenses, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ResourcesDiscoverApi.getV2ResourcesDiscoverLicenses, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v2/resources/discover/licenses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with,
            'with', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
