<?php
/**
 * PostV2ResourcesCreatorCouponsRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BuiltByBit API
 *
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostV2ResourcesCreatorCouponsRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostV2ResourcesCreatorCouponsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'post_v2_resources_creator_coupons_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'discount' => 'float',
        'label' => 'string',
        'do_expiry' => 'bool',
        'expiry_date' => 'string',
        'limited_uses' => 'bool',
        'max_uses' => 'int',
        'limited_user_uses' => 'bool',
        'max_per_user_uses' => 'int',
        'all_content_types' => 'string[]',
        'resources' => 'string',
        'addons' => 'string',
        'bundles' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'discount' => null,
        'label' => null,
        'do_expiry' => null,
        'expiry_date' => null,
        'limited_uses' => null,
        'max_uses' => null,
        'limited_user_uses' => null,
        'max_per_user_uses' => null,
        'all_content_types' => null,
        'resources' => null,
        'addons' => null,
        'bundles' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'discount' => false,
        'label' => false,
        'do_expiry' => false,
        'expiry_date' => false,
        'limited_uses' => false,
        'max_uses' => false,
        'limited_user_uses' => false,
        'max_per_user_uses' => false,
        'all_content_types' => false,
        'resources' => false,
        'addons' => false,
        'bundles' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'discount' => 'discount',
        'label' => 'label',
        'do_expiry' => 'do_expiry',
        'expiry_date' => 'expiry_date',
        'limited_uses' => 'limited_uses',
        'max_uses' => 'max_uses',
        'limited_user_uses' => 'limited_user_uses',
        'max_per_user_uses' => 'max_per_user_uses',
        'all_content_types' => 'all_content_types',
        'resources' => 'resources',
        'addons' => 'addons',
        'bundles' => 'bundles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'discount' => 'setDiscount',
        'label' => 'setLabel',
        'do_expiry' => 'setDoExpiry',
        'expiry_date' => 'setExpiryDate',
        'limited_uses' => 'setLimitedUses',
        'max_uses' => 'setMaxUses',
        'limited_user_uses' => 'setLimitedUserUses',
        'max_per_user_uses' => 'setMaxPerUserUses',
        'all_content_types' => 'setAllContentTypes',
        'resources' => 'setResources',
        'addons' => 'setAddons',
        'bundles' => 'setBundles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'discount' => 'getDiscount',
        'label' => 'getLabel',
        'do_expiry' => 'getDoExpiry',
        'expiry_date' => 'getExpiryDate',
        'limited_uses' => 'getLimitedUses',
        'max_uses' => 'getMaxUses',
        'limited_user_uses' => 'getLimitedUserUses',
        'max_per_user_uses' => 'getMaxPerUserUses',
        'all_content_types' => 'getAllContentTypes',
        'resources' => 'getResources',
        'addons' => 'getAddons',
        'bundles' => 'getBundles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('do_expiry', $data ?? [], null);
        $this->setIfExists('expiry_date', $data ?? [], null);
        $this->setIfExists('limited_uses', $data ?? [], null);
        $this->setIfExists('max_uses', $data ?? [], null);
        $this->setIfExists('limited_user_uses', $data ?? [], null);
        $this->setIfExists('max_per_user_uses', $data ?? [], null);
        $this->setIfExists('all_content_types', $data ?? [], null);
        $this->setIfExists('resources', $data ?? [], null);
        $this->setIfExists('addons', $data ?? [], null);
        $this->setIfExists('bundles', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['discount'] === null) {
            $invalidProperties[] = "'discount' can't be null";
        }
        if (($this->container['discount'] > 50)) {
            $invalidProperties[] = "invalid value for 'discount', must be smaller than or equal to 50.";
        }

        if (($this->container['discount'] < 1)) {
            $invalidProperties[] = "invalid value for 'discount', must be bigger than or equal to 1.";
        }

        if ($this->container['label'] === null) {
            $invalidProperties[] = "'label' can't be null";
        }
        if ((mb_strlen($this->container['label']) > 15)) {
            $invalidProperties[] = "invalid value for 'label', the character length must be smaller than or equal to 15.";
        }

        if ((mb_strlen($this->container['label']) < 1)) {
            $invalidProperties[] = "invalid value for 'label', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Must be 'perecent'.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return float
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param float $discount discount
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }

        if (($discount > 50)) {
            throw new \InvalidArgumentException('invalid value for $discount when calling PostV2ResourcesCreatorCouponsRequest., must be smaller than or equal to 50.');
        }
        if (($discount < 1)) {
            throw new \InvalidArgumentException('invalid value for $discount when calling PostV2ResourcesCreatorCouponsRequest., must be bigger than or equal to 1.');
        }

        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string $label The trailing part of the coupon code (without '{user_id}-').
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        if ((mb_strlen($label) > 15)) {
            throw new \InvalidArgumentException('invalid length for $label when calling PostV2ResourcesCreatorCouponsRequest., must be smaller than or equal to 15.');
        }
        if ((mb_strlen($label) < 1)) {
            throw new \InvalidArgumentException('invalid length for $label when calling PostV2ResourcesCreatorCouponsRequest., must be bigger than or equal to 1.');
        }

        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets do_expiry
     *
     * @return bool|null
     */
    public function getDoExpiry()
    {
        return $this->container['do_expiry'];
    }

    /**
     * Sets do_expiry
     *
     * @param bool|null $do_expiry Whether or not to respect the 'expiry_date' field. No expiry date is set otherwise.
     *
     * @return self
     */
    public function setDoExpiry($do_expiry)
    {
        if (is_null($do_expiry)) {
            throw new \InvalidArgumentException('non-nullable do_expiry cannot be null');
        }
        $this->container['do_expiry'] = $do_expiry;

        return $this;
    }

    /**
     * Gets expiry_date
     *
     * @return string|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiry_date'];
    }

    /**
     * Sets expiry_date
     *
     * @param string|null $expiry_date expiry_date
     *
     * @return self
     */
    public function setExpiryDate($expiry_date)
    {
        if (is_null($expiry_date)) {
            throw new \InvalidArgumentException('non-nullable expiry_date cannot be null');
        }
        $this->container['expiry_date'] = $expiry_date;

        return $this;
    }

    /**
     * Gets limited_uses
     *
     * @return bool|null
     */
    public function getLimitedUses()
    {
        return $this->container['limited_uses'];
    }

    /**
     * Sets limited_uses
     *
     * @param bool|null $limited_uses Whether or not to respect the 'max_uses' field. No max use limit is set otherwise.
     *
     * @return self
     */
    public function setLimitedUses($limited_uses)
    {
        if (is_null($limited_uses)) {
            throw new \InvalidArgumentException('non-nullable limited_uses cannot be null');
        }
        $this->container['limited_uses'] = $limited_uses;

        return $this;
    }

    /**
     * Gets max_uses
     *
     * @return int|null
     */
    public function getMaxUses()
    {
        return $this->container['max_uses'];
    }

    /**
     * Sets max_uses
     *
     * @param int|null $max_uses max_uses
     *
     * @return self
     */
    public function setMaxUses($max_uses)
    {
        if (is_null($max_uses)) {
            throw new \InvalidArgumentException('non-nullable max_uses cannot be null');
        }
        $this->container['max_uses'] = $max_uses;

        return $this;
    }

    /**
     * Gets limited_user_uses
     *
     * @return bool|null
     */
    public function getLimitedUserUses()
    {
        return $this->container['limited_user_uses'];
    }

    /**
     * Sets limited_user_uses
     *
     * @param bool|null $limited_user_uses Whether or not to respect the 'max_per_user_uses' field. No max uses per user limit is set otherwise.
     *
     * @return self
     */
    public function setLimitedUserUses($limited_user_uses)
    {
        if (is_null($limited_user_uses)) {
            throw new \InvalidArgumentException('non-nullable limited_user_uses cannot be null');
        }
        $this->container['limited_user_uses'] = $limited_user_uses;

        return $this;
    }

    /**
     * Gets max_per_user_uses
     *
     * @return int|null
     */
    public function getMaxPerUserUses()
    {
        return $this->container['max_per_user_uses'];
    }

    /**
     * Sets max_per_user_uses
     *
     * @param int|null $max_per_user_uses max_per_user_uses
     *
     * @return self
     */
    public function setMaxPerUserUses($max_per_user_uses)
    {
        if (is_null($max_per_user_uses)) {
            throw new \InvalidArgumentException('non-nullable max_per_user_uses cannot be null');
        }
        $this->container['max_per_user_uses'] = $max_per_user_uses;

        return $this;
    }

    /**
     * Gets all_content_types
     *
     * @return string[]|null
     */
    public function getAllContentTypes()
    {
        return $this->container['all_content_types'];
    }

    /**
     * Sets all_content_types
     *
     * @param string[]|null $all_content_types If a content type is included, all of the creator's content (of that type) can be used against this coupon.  Support values include: 'resource', 'addon', and 'bundle'
     *
     * @return self
     */
    public function setAllContentTypes($all_content_types)
    {
        if (is_null($all_content_types)) {
            throw new \InvalidArgumentException('non-nullable all_content_types cannot be null');
        }
        $this->container['all_content_types'] = $all_content_types;

        return $this;
    }

    /**
     * Gets resources
     *
     * @return string|null
     */
    public function getResources()
    {
        return $this->container['resources'];
    }

    /**
     * Sets resources
     *
     * @param string|null $resources A comma-separated list of resource IDs which this coupon can be used against.
     *
     * @return self
     */
    public function setResources($resources)
    {
        if (is_null($resources)) {
            throw new \InvalidArgumentException('non-nullable resources cannot be null');
        }
        $this->container['resources'] = $resources;

        return $this;
    }

    /**
     * Gets addons
     *
     * @return string|null
     */
    public function getAddons()
    {
        return $this->container['addons'];
    }

    /**
     * Sets addons
     *
     * @param string|null $addons A comma-separated list of addon IDs which this coupon can be used against.
     *
     * @return self
     */
    public function setAddons($addons)
    {
        if (is_null($addons)) {
            throw new \InvalidArgumentException('non-nullable addons cannot be null');
        }
        $this->container['addons'] = $addons;

        return $this;
    }

    /**
     * Gets bundles
     *
     * @return string|null
     */
    public function getBundles()
    {
        return $this->container['bundles'];
    }

    /**
     * Sets bundles
     *
     * @param string|null $bundles A comma-separated list of bundle IDs which this coupon can be used against.
     *
     * @return self
     */
    public function setBundles($bundles)
    {
        if (is_null($bundles)) {
            throw new \InvalidArgumentException('non-nullable bundles cannot be null');
        }
        $this->container['bundles'] = $bundles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


