<?php
/**
 * Resource
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BuiltByBit API
 *
 * All operations not tagged 'free' require an active [Ultimate](https://builtbybit.com/account/ultimate) subscription or invite-only permissions.    V2 documentation: https://builtbybit.com/wiki/api-v2/ \\  OAuth2 documentation: https://builtbybit.com/wiki/oauth2/
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Resource Class Doc Comment
 *
 * @category Class
 * @description Supported &#39;with&#39; values: - &#39;Creator&#39;: the resource creator/owner - &#39;Category&#39;: the resource category  - &#39;Description&#39;: the resource description (rendered HTML and BBCode) - &#39;LatestReviews&#39;: list of the 10 latest reviews - &#39;Filter values&#39;: filter values set by the creator
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Resource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Resource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'resource_id' => 'int',
        'title' => 'string',
        'summary' => 'string',
        'url' => 'string',
        'creator_id' => 'int',
        'published_at' => 'int',
        'last_updated_at' => 'int',
        'purchases' => 'int',
        'downloads' => 'int',
        'cover_image_url' => 'string',
        'carousel_image_urls' => 'string[]',
        'review_count' => 'int',
        'review_average' => 'float',
        'list_price' => '\OpenAPI\Client\Model\Price',
        'final_price' => '\OpenAPI\Client\Model\Price',
        'sale_event_entry' => '\OpenAPI\Client\Model\SaleEventEntry',
        'creator' => '\OpenAPI\Client\Model\Member',
        'latest_version' => '\OpenAPI\Client\Model\Version',
        'latest_update' => '\OpenAPI\Client\Model\Version',
        'latest_reviews' => '\OpenAPI\Client\Model\Review[]',
        'description' => '\OpenAPI\Client\Model\Description',
        'category' => '\OpenAPI\Client\Model\Category',
        'addons' => 'array<string,\OpenAPI\Client\Model\Addon[]>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'resource_id' => null,
        'title' => null,
        'summary' => null,
        'url' => null,
        'creator_id' => null,
        'published_at' => null,
        'last_updated_at' => null,
        'purchases' => null,
        'downloads' => null,
        'cover_image_url' => null,
        'carousel_image_urls' => null,
        'review_count' => null,
        'review_average' => null,
        'list_price' => null,
        'final_price' => null,
        'sale_event_entry' => null,
        'creator' => null,
        'latest_version' => null,
        'latest_update' => null,
        'latest_reviews' => null,
        'description' => null,
        'category' => null,
        'addons' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'resource_id' => false,
        'title' => false,
        'summary' => false,
        'url' => false,
        'creator_id' => false,
        'published_at' => false,
        'last_updated_at' => false,
        'purchases' => false,
        'downloads' => false,
        'cover_image_url' => false,
        'carousel_image_urls' => false,
        'review_count' => false,
        'review_average' => false,
        'list_price' => false,
        'final_price' => false,
        'sale_event_entry' => false,
        'creator' => false,
        'latest_version' => false,
        'latest_update' => false,
        'latest_reviews' => false,
        'description' => false,
        'category' => false,
        'addons' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'resource_id' => 'resource_id',
        'title' => 'title',
        'summary' => 'summary',
        'url' => 'url',
        'creator_id' => 'creator_id',
        'published_at' => 'published_at',
        'last_updated_at' => 'last_updated_at',
        'purchases' => 'purchases',
        'downloads' => 'downloads',
        'cover_image_url' => 'cover_image_url',
        'carousel_image_urls' => 'carousel_image_urls',
        'review_count' => 'review_count',
        'review_average' => 'review_average',
        'list_price' => 'ListPrice',
        'final_price' => 'FinalPrice',
        'sale_event_entry' => 'SaleEventEntry',
        'creator' => 'Creator',
        'latest_version' => 'LatestVersion',
        'latest_update' => 'LatestUpdate',
        'latest_reviews' => 'LatestReviews',
        'description' => 'Description',
        'category' => 'Category',
        'addons' => 'Addons'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'resource_id' => 'setResourceId',
        'title' => 'setTitle',
        'summary' => 'setSummary',
        'url' => 'setUrl',
        'creator_id' => 'setCreatorId',
        'published_at' => 'setPublishedAt',
        'last_updated_at' => 'setLastUpdatedAt',
        'purchases' => 'setPurchases',
        'downloads' => 'setDownloads',
        'cover_image_url' => 'setCoverImageUrl',
        'carousel_image_urls' => 'setCarouselImageUrls',
        'review_count' => 'setReviewCount',
        'review_average' => 'setReviewAverage',
        'list_price' => 'setListPrice',
        'final_price' => 'setFinalPrice',
        'sale_event_entry' => 'setSaleEventEntry',
        'creator' => 'setCreator',
        'latest_version' => 'setLatestVersion',
        'latest_update' => 'setLatestUpdate',
        'latest_reviews' => 'setLatestReviews',
        'description' => 'setDescription',
        'category' => 'setCategory',
        'addons' => 'setAddons'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'resource_id' => 'getResourceId',
        'title' => 'getTitle',
        'summary' => 'getSummary',
        'url' => 'getUrl',
        'creator_id' => 'getCreatorId',
        'published_at' => 'getPublishedAt',
        'last_updated_at' => 'getLastUpdatedAt',
        'purchases' => 'getPurchases',
        'downloads' => 'getDownloads',
        'cover_image_url' => 'getCoverImageUrl',
        'carousel_image_urls' => 'getCarouselImageUrls',
        'review_count' => 'getReviewCount',
        'review_average' => 'getReviewAverage',
        'list_price' => 'getListPrice',
        'final_price' => 'getFinalPrice',
        'sale_event_entry' => 'getSaleEventEntry',
        'creator' => 'getCreator',
        'latest_version' => 'getLatestVersion',
        'latest_update' => 'getLatestUpdate',
        'latest_reviews' => 'getLatestReviews',
        'description' => 'getDescription',
        'category' => 'getCategory',
        'addons' => 'getAddons'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('resource_id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('summary', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('creator_id', $data ?? [], null);
        $this->setIfExists('published_at', $data ?? [], null);
        $this->setIfExists('last_updated_at', $data ?? [], null);
        $this->setIfExists('purchases', $data ?? [], null);
        $this->setIfExists('downloads', $data ?? [], null);
        $this->setIfExists('cover_image_url', $data ?? [], null);
        $this->setIfExists('carousel_image_urls', $data ?? [], null);
        $this->setIfExists('review_count', $data ?? [], null);
        $this->setIfExists('review_average', $data ?? [], null);
        $this->setIfExists('list_price', $data ?? [], null);
        $this->setIfExists('final_price', $data ?? [], null);
        $this->setIfExists('sale_event_entry', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('latest_version', $data ?? [], null);
        $this->setIfExists('latest_update', $data ?? [], null);
        $this->setIfExists('latest_reviews', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('addons', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets resource_id
     *
     * @return int|null
     */
    public function getResourceId()
    {
        return $this->container['resource_id'];
    }

    /**
     * Sets resource_id
     *
     * @param int|null $resource_id resource_id
     *
     * @return self
     */
    public function setResourceId($resource_id)
    {
        if (is_null($resource_id)) {
            throw new \InvalidArgumentException('non-nullable resource_id cannot be null');
        }
        $this->container['resource_id'] = $resource_id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string|null $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets creator_id
     *
     * @return int|null
     */
    public function getCreatorId()
    {
        return $this->container['creator_id'];
    }

    /**
     * Sets creator_id
     *
     * @param int|null $creator_id creator_id
     *
     * @return self
     */
    public function setCreatorId($creator_id)
    {
        if (is_null($creator_id)) {
            throw new \InvalidArgumentException('non-nullable creator_id cannot be null');
        }
        $this->container['creator_id'] = $creator_id;

        return $this;
    }

    /**
     * Gets published_at
     *
     * @return int|null
     */
    public function getPublishedAt()
    {
        return $this->container['published_at'];
    }

    /**
     * Sets published_at
     *
     * @param int|null $published_at published_at
     *
     * @return self
     */
    public function setPublishedAt($published_at)
    {
        if (is_null($published_at)) {
            throw new \InvalidArgumentException('non-nullable published_at cannot be null');
        }
        $this->container['published_at'] = $published_at;

        return $this;
    }

    /**
     * Gets last_updated_at
     *
     * @return int|null
     */
    public function getLastUpdatedAt()
    {
        return $this->container['last_updated_at'];
    }

    /**
     * Sets last_updated_at
     *
     * @param int|null $last_updated_at last_updated_at
     *
     * @return self
     */
    public function setLastUpdatedAt($last_updated_at)
    {
        if (is_null($last_updated_at)) {
            throw new \InvalidArgumentException('non-nullable last_updated_at cannot be null');
        }
        $this->container['last_updated_at'] = $last_updated_at;

        return $this;
    }

    /**
     * Gets purchases
     *
     * @return int|null
     */
    public function getPurchases()
    {
        return $this->container['purchases'];
    }

    /**
     * Sets purchases
     *
     * @param int|null $purchases purchases
     *
     * @return self
     */
    public function setPurchases($purchases)
    {
        if (is_null($purchases)) {
            throw new \InvalidArgumentException('non-nullable purchases cannot be null');
        }
        $this->container['purchases'] = $purchases;

        return $this;
    }

    /**
     * Gets downloads
     *
     * @return int|null
     */
    public function getDownloads()
    {
        return $this->container['downloads'];
    }

    /**
     * Sets downloads
     *
     * @param int|null $downloads downloads
     *
     * @return self
     */
    public function setDownloads($downloads)
    {
        if (is_null($downloads)) {
            throw new \InvalidArgumentException('non-nullable downloads cannot be null');
        }
        $this->container['downloads'] = $downloads;

        return $this;
    }

    /**
     * Gets cover_image_url
     *
     * @return string|null
     */
    public function getCoverImageUrl()
    {
        return $this->container['cover_image_url'];
    }

    /**
     * Sets cover_image_url
     *
     * @param string|null $cover_image_url cover_image_url
     *
     * @return self
     */
    public function setCoverImageUrl($cover_image_url)
    {
        if (is_null($cover_image_url)) {
            throw new \InvalidArgumentException('non-nullable cover_image_url cannot be null');
        }
        $this->container['cover_image_url'] = $cover_image_url;

        return $this;
    }

    /**
     * Gets carousel_image_urls
     *
     * @return string[]|null
     */
    public function getCarouselImageUrls()
    {
        return $this->container['carousel_image_urls'];
    }

    /**
     * Sets carousel_image_urls
     *
     * @param string[]|null $carousel_image_urls carousel_image_urls
     *
     * @return self
     */
    public function setCarouselImageUrls($carousel_image_urls)
    {
        if (is_null($carousel_image_urls)) {
            throw new \InvalidArgumentException('non-nullable carousel_image_urls cannot be null');
        }
        $this->container['carousel_image_urls'] = $carousel_image_urls;

        return $this;
    }

    /**
     * Gets review_count
     *
     * @return int|null
     */
    public function getReviewCount()
    {
        return $this->container['review_count'];
    }

    /**
     * Sets review_count
     *
     * @param int|null $review_count review_count
     *
     * @return self
     */
    public function setReviewCount($review_count)
    {
        if (is_null($review_count)) {
            throw new \InvalidArgumentException('non-nullable review_count cannot be null');
        }
        $this->container['review_count'] = $review_count;

        return $this;
    }

    /**
     * Gets review_average
     *
     * @return float|null
     */
    public function getReviewAverage()
    {
        return $this->container['review_average'];
    }

    /**
     * Sets review_average
     *
     * @param float|null $review_average review_average
     *
     * @return self
     */
    public function setReviewAverage($review_average)
    {
        if (is_null($review_average)) {
            throw new \InvalidArgumentException('non-nullable review_average cannot be null');
        }
        $this->container['review_average'] = $review_average;

        return $this;
    }

    /**
     * Gets list_price
     *
     * @return \OpenAPI\Client\Model\Price|null
     */
    public function getListPrice()
    {
        return $this->container['list_price'];
    }

    /**
     * Sets list_price
     *
     * @param \OpenAPI\Client\Model\Price|null $list_price list_price
     *
     * @return self
     */
    public function setListPrice($list_price)
    {
        if (is_null($list_price)) {
            throw new \InvalidArgumentException('non-nullable list_price cannot be null');
        }
        $this->container['list_price'] = $list_price;

        return $this;
    }

    /**
     * Gets final_price
     *
     * @return \OpenAPI\Client\Model\Price|null
     */
    public function getFinalPrice()
    {
        return $this->container['final_price'];
    }

    /**
     * Sets final_price
     *
     * @param \OpenAPI\Client\Model\Price|null $final_price final_price
     *
     * @return self
     */
    public function setFinalPrice($final_price)
    {
        if (is_null($final_price)) {
            throw new \InvalidArgumentException('non-nullable final_price cannot be null');
        }
        $this->container['final_price'] = $final_price;

        return $this;
    }

    /**
     * Gets sale_event_entry
     *
     * @return \OpenAPI\Client\Model\SaleEventEntry|null
     */
    public function getSaleEventEntry()
    {
        return $this->container['sale_event_entry'];
    }

    /**
     * Sets sale_event_entry
     *
     * @param \OpenAPI\Client\Model\SaleEventEntry|null $sale_event_entry sale_event_entry
     *
     * @return self
     */
    public function setSaleEventEntry($sale_event_entry)
    {
        if (is_null($sale_event_entry)) {
            throw new \InvalidArgumentException('non-nullable sale_event_entry cannot be null');
        }
        $this->container['sale_event_entry'] = $sale_event_entry;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return \OpenAPI\Client\Model\Member|null
     */
    public function getCreator()
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param \OpenAPI\Client\Model\Member|null $creator creator
     *
     * @return self
     */
    public function setCreator($creator)
    {
        if (is_null($creator)) {
            throw new \InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets latest_version
     *
     * @return \OpenAPI\Client\Model\Version|null
     */
    public function getLatestVersion()
    {
        return $this->container['latest_version'];
    }

    /**
     * Sets latest_version
     *
     * @param \OpenAPI\Client\Model\Version|null $latest_version latest_version
     *
     * @return self
     */
    public function setLatestVersion($latest_version)
    {
        if (is_null($latest_version)) {
            throw new \InvalidArgumentException('non-nullable latest_version cannot be null');
        }
        $this->container['latest_version'] = $latest_version;

        return $this;
    }

    /**
     * Gets latest_update
     *
     * @return \OpenAPI\Client\Model\Version|null
     */
    public function getLatestUpdate()
    {
        return $this->container['latest_update'];
    }

    /**
     * Sets latest_update
     *
     * @param \OpenAPI\Client\Model\Version|null $latest_update latest_update
     *
     * @return self
     */
    public function setLatestUpdate($latest_update)
    {
        if (is_null($latest_update)) {
            throw new \InvalidArgumentException('non-nullable latest_update cannot be null');
        }
        $this->container['latest_update'] = $latest_update;

        return $this;
    }

    /**
     * Gets latest_reviews
     *
     * @return \OpenAPI\Client\Model\Review[]|null
     */
    public function getLatestReviews()
    {
        return $this->container['latest_reviews'];
    }

    /**
     * Sets latest_reviews
     *
     * @param \OpenAPI\Client\Model\Review[]|null $latest_reviews latest_reviews
     *
     * @return self
     */
    public function setLatestReviews($latest_reviews)
    {
        if (is_null($latest_reviews)) {
            throw new \InvalidArgumentException('non-nullable latest_reviews cannot be null');
        }
        $this->container['latest_reviews'] = $latest_reviews;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \OpenAPI\Client\Model\Description|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \OpenAPI\Client\Model\Description|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \OpenAPI\Client\Model\Category|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \OpenAPI\Client\Model\Category|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets addons
     *
     * @return array<string,\OpenAPI\Client\Model\Addon[]>|null
     */
    public function getAddons()
    {
        return $this->container['addons'];
    }

    /**
     * Sets addons
     *
     * @param array<string,\OpenAPI\Client\Model\Addon[]>|null $addons addons
     *
     * @return self
     */
    public function setAddons($addons)
    {
        if (is_null($addons)) {
            throw new \InvalidArgumentException('non-nullable addons cannot be null');
        }
        $this->container['addons'] = $addons;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


